springfox:
  documentation:
    swagger-ui:
      enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
spring:
  datasource:
    druid:
      filter-class-names:
